//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttributeAnalyzer_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttributeAnalyzer_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphify.AttributeAnalyzer.Resources", typeof(AttributeAnalyzer_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type already implements the Clone method, rendering Graphify redundant..
        /// </summary>
        internal static string AlreadyImplementsRuleDescription {
            get {
                return ResourceManager.GetString("AlreadyImplementsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type already implements the Clone method, rendering Graphify redundant..
        /// </summary>
        internal static string AlreadyImplementsRuleMessageFormat {
            get {
                return ResourceManager.GetString("AlreadyImplementsRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type already implements Clone.
        /// </summary>
        internal static string AlreadyImplementsRuleTitle {
            get {
                return ResourceManager.GetString("AlreadyImplementsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Graphify attribute is only supported on type declarations..
        /// </summary>
        internal static string CompatibleTargetTypeRuleDescription {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Graphify attribute is only supported on type declarations..
        /// </summary>
        internal static string CompatibleTargetTypeRuleMessageFormat {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not compatible with Graphify.
        /// </summary>
        internal static string CompatibleTargetTypeRuleTitle {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be marked as Partial to facilitate code generation..
        /// </summary>
        internal static string PartialTypeRuleDescription {
            get {
                return ResourceManager.GetString("PartialTypeRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` must be marked as Partial to facilitate code generation..
        /// </summary>
        internal static string PartialTypeRuleMessageFormat {
            get {
                return ResourceManager.GetString("PartialTypeRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not Partial.
        /// </summary>
        internal static string PartialTypeRuleTitle {
            get {
                return ResourceManager.GetString("PartialTypeRuleTitle", resourceCulture);
            }
        }
    }
}
