namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Graphify attribute, used to denote when a type should serve as a wrapper for a single value.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class GraphifyAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "GraphifyAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Graphify";

        private const string GraphifyMetadataName = "Graphify.GraphifyAttribute";

        /// <summary>
        /// Gets the generated source content as a formatted string.
        /// </summary>
        /// <value>
        /// The generated source content as a formatted string.
        /// </value>
        internal static string Content { get; } = string.Format(GraphifyAttributeGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(GraphifyMetadataName) is null)
            {
                var text = SourceText.From(Content, Encoding.UTF8);

                context.AddSource(Hint, text);
            }
        }
    }
}