namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Ignore attribute, used to denote when a property of a class should be ignored.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class IgnoreAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "IgnoreAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Ignore";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the ignore attribute generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by the ignore attribute generator.
        /// </value>
        internal static string Content { get; } = string.Format(IgnoreAttributeGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            var text = SourceText.From(Content, Encoding.UTF8);

            context.AddSource(Hint, text);
        }
    }
}