namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Inspector Contract, to be used to register an "interest" in notifications relating to specific sections along the hierarchy
    /// of the instance for synchronous graph traversal.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class InspectorContractGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Inspector.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Inspector";

        private const string InspectorMetadataName = "Graphify.IInspector`2";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by generator.
        /// </value>
        internal static string Content { get; } = string.Format(InspectorContractGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(InspectorMetadataName) is null)
            {
                var text = SourceText.From(Content, Encoding.UTF8);

                context.AddSource(Hint, text);
            }
        }
    }
}
