namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the base Navigator, to be used to register scan an object graph and notify any "interested" observes.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class NavigatorGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Navigator.Base.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Navigator";

        private const string NavigatorMetadataName = "Graphify.Navigator`1";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by generator.
        /// </value>
        internal static string Content { get; } = string.Format(NavigatorGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(NavigatorMetadataName) is null)
            {
                var text = SourceText.From(Content, Encoding.UTF8);

                context.AddSource(Hint, text);
            }
        }
    }
}