namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates asynchronous navigator helper extensions.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class NavigatorExtensionsGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "NavigatorExtensions.g.cs";

        private const string NavigatorExtensionsMetadataName = "Graphify.NavigatorExtensions";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        internal static string Content { get; } = NavigatorExtensionsGenerator_Resources.Content;

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(NavigatorExtensionsMetadataName) is null)
            {
                context.AddSource(Hint, SourceText.From(Content, Encoding.UTF8));
            }
        }
    }
}