namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Navigator Contract, to be used to register scan an object graph and notify any "interested" observes.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class NavigatorContractGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Navigator.Contract.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Navigator";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by generator.
        /// </value>
        internal static string Content { get; } = string.Format(NavigatorContractGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            var text = SourceText.From(Content, Encoding.UTF8);

            context.AddSource(Hint, text);
        }
    }
}