namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates navigator helper extensions.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class NavigatorExtensionsGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Navigator.Extensions.g.cs";

        /// <summary>
        /// The name of the generated type.
        /// </summary>
        internal const string Name = "NavigatorExtensions";

        private const string NavigatorMetadataName = "Graphify.NavigatorExtensions";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        internal static string Content { get; } = string.Format(NavigatorExtensionsGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(NavigatorMetadataName) is null)
            {
                var text = SourceText.From(Content, Encoding.UTF8);

                context.AddSource(Hint, text);
            }
        }
    }
}
