namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Traverse attribute, used to denote how a property of a class should be traversed.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class TraverseAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "TraverseAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Traverse";

        private const string TraverseMetadataName = "Graphify.TraverseAttribute";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the traverse attribute generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by the traverse attribute generator.
        /// </value>
        internal static string Content { get; } = string.Format(TraverseAttributeGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(TraverseMetadataName) is null)
            {
                var text = SourceText.From(Content, Encoding.UTF8);

                context.AddSource(Hint, text);
            }
        }
    }
}