namespace Graphify
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    /// <summary>
    /// Generates the Visitor Contract, to be used to register an "interest" in notifications relating to specific sections along the heirarchy
    /// of the instance.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class VisitorContractGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Visitor.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Visitor";

        private const string VisitorMetadataName = "Graphify.IVisitor`2";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by generator.
        /// </value>
        internal static string Content { get; } = string.Format(VisitorContractGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, Generate);
        }

        private static void Generate(SourceProductionContext context, Compilation compilation)
        {
            if (compilation.GetTypeByMetadataName(VisitorMetadataName) is not null)
            {
                return;
            }

            var text = SourceText.From(Content, Encoding.UTF8);

            context.AddSource(Hint, text);
        }
    }
}