//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsynchronousNavigatorStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsynchronousNavigatorStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphify.Strategies.AsynchronousNavigatorStrategy.Resources", typeof(AsynchronousNavigatorStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = _provider.Concat(results, Navigate{0}&lt;TResult&gt;({1}root, element.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForElementContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = _provider.Concat(results, Navigate{0}&lt;TResult&gt;({1}root, value.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = _provider.Concat(results, Navigate{0}&lt;TResult&gt;({1}root, value, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForPropertyElement {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForPropertyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = _provider.Concat(results, Navigate{0}&lt;TResult&gt;(root, root.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForSubjectContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForSubjectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({1}{0} root, {2} value, global::System.Threading.CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = _provider.Empty&lt;TResult&gt;();
        ///
        ///    _ = _provider.HasVisitors(out global::System.Collections.Generic.IEnumerable&lt;global::Graphify.IVisitor&lt;{3}, TResult&gt;&gt; observers);
        ///
        ///    int index = 0;
        ///
        ///    foreach ({8} element in value)
        ///    {{
        ///        var {9} = new  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForElementContent {
            get {
                return ResourceManager.GetString("GenerateContentForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({1}{0} root, {2} value, global::System.Threading.CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = _provider.Empty&lt;TResult&gt;();
        ///    var {9} = new {3}({4}root, value);
        ///
        ///    if (_provider.HasVisitors(out global::System.Collections.Generic.IEnumerable&lt;global::Graphify.IVisitor&lt;{3}, TResult&gt;&gt; observers))
        ///    {{
        ///        results = _provider.Concat(results [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateContentForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if NET5_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        ///{0} sealed partial class {1}
        ///{{
        ///    {3}
        ///}}
        ///#endif.
        /// </summary>
        internal static string GenerateContentNest {
            get {
                return ResourceManager.GetString("GenerateContentNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if NET5_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        ///{0} sealed partial class {1}
        ///    : {2}
        ///{{
        ///    private readonly global::System.IServiceProvider _provider;
        ///
        ///    public {1}(global::System.IServiceProvider provider)
        ///    {{
        ///        if (global::System.Object.ReferenceEquals(provider, null))
        ///        {{
        ///            throw new global::System.ArgumentNullException(&quot;provider&quot;);
        ///        }}
        ///
        ///        _provider = provider;
        ///    }}
        ///
        ///    public global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateNavigatorContent {
            get {
                return ResourceManager.GetString("GenerateNavigatorContent", resourceCulture);
            }
        }
    }
}
