//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphify.Strategies.ClassStrategy.Resources", typeof(ClassStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public sealed partial class {1}
        ///{{
        ///    internal {1}(int index, {2} root, {3}{4} value)
        ///    {{{5}
        ///        Index = index;
        ///        Root = root;
        ///        Value = value;
        ///    }}
        ///
        ///    public int Index {{ get; private set; }}
        ///
        ///    public {2} Root {{ get; private set; }}
        ///{6}
        ///    public {4} Value {{ get; private set; }}
        ///}}.
        /// </summary>
        internal static string GenerateClassForElementContent {
            get {
                return ResourceManager.GetString("GenerateClassForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public sealed partial class {1}
        ///{{
        ///    internal {1}({2} root, {3}{4} value)
        ///    {{{5}
        ///        Root = root;
        ///        Value = value;
        ///    }}
        ///
        ///    public {2} Root {{ get; private set; }}
        ///{6}
        ///    public {4} Value {{ get; private set; }}
        ///}}.
        /// </summary>
        internal static string GenerateClassForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateClassForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}, .
        /// </summary>
        internal static string GeneratePropertyContentArgument {
            get {
                return ResourceManager.GetString("GeneratePropertyContentArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0} = {1};.
        /// </summary>
        internal static string GeneratePropertyContentAssignment {
            get {
                return ResourceManager.GetString("GeneratePropertyContentAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     public {0} {1} {{ get; private set; }}.
        /// </summary>
        internal static string GeneratePropertyContentDeclaration {
            get {
                return ResourceManager.GetString("GeneratePropertyContentDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial class {0}
        ///{{
        ///    {1}
        ///}}.
        /// </summary>
        internal static string GenerateWrapperDeclarationsContent {
            get {
                return ResourceManager.GetString("GenerateWrapperDeclarationsContent", resourceCulture);
            }
        }
    }
}
