//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImplementationStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImplementationStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphify.Strategies.ImplementationStrategy.Resources", typeof(ImplementationStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = Concat(results, Navigate{0}&lt;TResult&gt;(root, {1}value, element, element.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForElementContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = Concat(results, Navigate{0}&lt;TResult&gt;(root, {1}value, value.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = Concat(results, Navigate{0}&lt;TResult&gt;(root, {1}value, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForPropertyElement {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForPropertyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = Concat(results, Navigate{0}&lt;TResult&gt;(root, root.{2}, cancellationToken), cancellationToken);.
        /// </summary>
        internal static string GenerateConcatenationsForSubjectContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsForSubjectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({0} root, {1}{2} value, global::System.Threading.CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = Empty&lt;TResult&gt;();
        ///
        ///    _ = HasObservers(out global::System.Collections.Generic.IEnumerable&lt;global::Graphify.IVisitor&lt;{3}, TResult&gt;&gt; observers);
        ///
        ///    int index = 0;
        ///
        ///    foreach ({8} element in value)
        ///    {{
        ///        var instance = new {3}(index, roo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForElementContent {
            get {
                return ResourceManager.GetString("GenerateContentForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({0} root, {1}{2} value, global::System.Threading.CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = Empty&lt;TResult&gt;();
        ///
        ///    if (HasObservers(out global::System.Collections.Generic.IEnumerable&lt;global::Graphify.IVisitor&lt;{3}, TResult&gt;&gt; observers))
        ///    {{
        ///        var instance = new {3}(root, {4}value);
        ///
        ///        results = Concat(results, Invoke&lt;{3}, TRes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateContentForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed partial class {0}
        ///{{
        ///    {2}
        ///}}.
        /// </summary>
        internal static string GenerateContentNest {
            get {
                return ResourceManager.GetString("GenerateContentNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed partial class {0}
        ///    : global::Graphify.Navigator&lt;{2}&gt;,
        ///      {1}
        ///{{
        ///    public {0}(global::System.IServiceProvider provider)
        ///        : base(provider)
        ///    {{
        ///    }}
        ///
        ///    public override IAsyncEnumerable&lt;TResult&gt; Navigate&lt;TResult&gt;({2} root, global::System.Threading.CancellationToken cancellationToken)
        ///    {{
        ///        var results = Empty&lt;TResult&gt;();
        ///
        ///        if (HasObservers&lt;{2}, TResult&gt;(out global::System.Collections.Generic.IEnumerable&lt;global::Graphify.IVisitor&lt;{2}, TResult&gt;&gt; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateNavigatorContent {
            get {
                return ResourceManager.GetString("GenerateNavigatorContent", resourceCulture);
            }
        }
    }
}
