//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImplementationStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImplementationStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphify.Strategies.ImplementationStrategy.Resources", typeof(ImplementationStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results = Concat(results, Navigate{0}(root, {1}, element, element.{2}));.
        /// </summary>
        internal static string GenerateConcatenationsContent {
            get {
                return ResourceManager.GetString("GenerateConcatenationsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed partial class {0}
        ///    : {1},
        ///      global::Graphify.Navigator&lt;{2}&gt;
        ///{{
        ///    public override IAsyncEnumerable&lt;TResult&gt; Navigate&lt;TResult&gt;({2} root, CancellationToken cancellationToken)
        ///    {{
        ///        var results = Empty&lt;TResult&gt;();
        ///        
        ///        {3}
        ///        
        ///        return results;
        ///    }}
        ///}}.
        /// </summary>
        internal static string GenerateContent {
            get {
                return ResourceManager.GetString("GenerateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({0} root, {1}{2} value, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = Empty&lt;TResult&gt;();
        ///
        ///    if (HasObservers(out global::System.Collections.Generic.IEnumerable&lt;IVisitor&lt;{3}, TResult&gt;&gt; observers))
        ///    {{
        ///        var instance = new {3}(root, {4}value);
        ///
        ///        foreach (IVisitor&lt;{3}, TRes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForElementContent {
            get {
                return ResourceManager.GetString("GenerateContentForElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; Navigate{7}&lt;TResult&gt;({0} root, {1}{2} value, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        ///{{
        ///    global::System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt; results = Empty&lt;TResult&gt;();
        ///
        ///    if (HasObservers(out global::System.Collections.Generic.IEnumerable&lt;IVisitor&lt;{3}, TResult&gt;&gt; observers))
        ///    {{
        ///        var instance = new {3}(root, {4}value);
        ///        
        ///        foreach (IVisitor&lt;{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateContentForPropertyContent {
            get {
                return ResourceManager.GetString("GenerateContentForPropertyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed partial class {0}
        ///{{
        ///    {2}
        ///}}.
        /// </summary>
        internal static string GenerateContentNest {
            get {
                return ResourceManager.GetString("GenerateContentNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed partial class {0}
        ///    : global::Graphify.Navigator&lt;{2}&gt;,
        ///      {1}
        ///{{
        ///    public override IAsyncEnumerable&lt;TResult&gt; Navigate&lt;TResult&gt;({2} instance, CancellationToken cancellationToken)
        ///    {{
        ///        var results = Empty&lt;TResult&gt;();
        ///
        ///        {3}
        ///
        ///        return results;
        ///    }}
        ///}}.
        /// </summary>
        internal static string GenerateNavigatorContent {
            get {
                return ResourceManager.GetString("GenerateNavigatorContent", resourceCulture);
            }
        }
    }
}
